# Generated by Django 2.2.9 on 2020-01-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_plan_id', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=15)),
                ('plan_type', models.CharField(choices=[('pro', 'Professional'), ('free', 'Free')], default='free', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('stripe_customer_id', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.Plan')),
            ],
        ),
    ]
