# Generated by Django 2.2.10 on 2020-02-18 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200119_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateField(default=datetime.date(2040, 1, 1)),
        ),
        migrations.AddField(
            model_name='subscription',
            name='downgrade_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
