# Generated by Django 2.2.10 on 2020-03-05 21:59

from django.db import migrations
from subscriptions.models import Plan

def generate_plans(apps, scheme_editor):
    free_plan = Plan.objects.create(
        stripe_plan_id='plan_GZrTcCGmKOLc5H',
        price=0,
        plan_type='free'
    )
    free_plan.save()

    pro_plan = Plan.objects.create(
        stripe_plan_id='plan_GZoeY9wrKLq1fa',
        price=15,
        plan_type='pro'
    )
    pro_plan.save()

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200218_0608'),
    ]

    operations = [
        migrations.RunPython(generate_plans)
    ]
