# Generated by Django 2.2.9 on 2020-01-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200119_2022'),
        ('common', '0002_auto_20200112_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.Subscription'),
        ),
    ]
