# Generated by Django 2.2.10 on 2020-02-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200119_2022'),
        ('common', '0005_hospital_email_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='subscription',
        ),
        migrations.AddField(
            model_name='hospital',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.Subscription'),
        ),
    ]
