# Generated by Django 2.2.10 on 2020-03-05 18:37

from django.db import migrations
from common.models import CustomUser

def generate_superuser(apps, schema_editor):
    superuser = CustomUser.objects.create_superuser(
        username='super1',
        email='super@super.com',
        password='123456superuser'
    )
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200218_0101'),
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
