# Generated by Django 2.2.9 on 2020-01-13 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20200112_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=100, verbose_name='name of patient')),
                ('notes', models.TextField()),
                ('created_on', models.DateField(verbose_name='examination creation date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='common.Doctor')),
            ],
        ),
    ]
