# Generated by Django 2.2.9 on 2020-01-12 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='examination creation date',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='name of patient',
        ),
        migrations.AddField(
            model_name='examination',
            name='created_on',
            field=models.DateField(default=datetime.date(2020, 1, 12), verbose_name='examination creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examination',
            name='pat_name',
            field=models.CharField(default='Gosho', max_length=100, verbose_name='name of patient'),
            preserve_default=False,
        ),
    ]
