# Generated by Django 2.2.10 on 2020-02-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_examination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='examination_type',
            field=models.CharField(choices=[('chest', 'Chest X-Ray'), ('elbow', 'Elbow X-Ray'), ('finger', 'Finger X-Ray'), ('forearm', 'Forearm X-Ray'), ('hand', 'Hand X-Ray'), ('humerus', 'Humerus X-Ray'), ('shoulder', 'Shoulder X-Ray'), ('wrist', 'Wrist X-Ray')], default='chest', max_length=15),
        ),
    ]
