# Generated by Django 2.2.10 on 2020-02-11 13:21

from django.db import migrations
from examinations.apps import ExaminationsConfig

def add_image_types_from_learner(apps, schema_editor):
    ImageType = apps.get_model('examinations', 'ImageType')
    for c in ExaminationsConfig.learner_image_type.data.classes:
       it = ImageType(label=c, human_readable=c.capitalize())
       it.save() 

def remove_image_types_from_learner(apps, schema_editor):
    ImageType = apps.get_model('examinations', 'ImageType')
    for c in ExaminationsConfig.learner_image_type.data.classes:
       it = ImageType.objects.get(label=c)
       it.delete() 

class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_auto_20200211_1520'),
    ]

    operations = [
        migrations.RunPython(add_image_types_from_learner, remove_image_types_from_learner)
    ]
