# Generated by Django 2.2.10 on 2020-02-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_auto_20200211_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_complete', models.BooleanField(default=False, verbose_name='the model was trained on this finding')),
                ('marked_for_training', models.BooleanField(default=False, verbose_name='the model will soon be trained on this finding')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.Examination')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.Finding')),
            ],
        ),
    ]
