# Generated by Django 2.2.10 on 2020-02-20 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0007_confirmedfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='conducted_on',
            field=models.DateField(default=datetime.date(2020, 2, 20)),
        ),
    ]
