# Generated by Django 2.2.10 on 2020-03-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0009_auto_20200220_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='examination_heatmaps/'),
        ),
    ]
